spring:
  application:
    name: pedido-api
  config:
    import: "optional:configserver:http://localhost:8888/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
    config:
      profile: pedido-dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: ["prometheus"]


