global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'Pedido-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["host.docker.internal:7788"]


  - job_name: 'Notificacao-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "host.docker.internal:8080" ]

  - job_name: 'Processador'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "host.docker.internal:8383" ]